value_true: "1"
micropost_items_per_page: 10
User_validates:
  min_lenght_password: 6
  max_lenght_email: 255
  max_lenght_name: 50
gravatar_size_default: 100
number_user_per_page: 10
password_reset_expired: 2
micropost_validates:
  max_lenght_content: 140
picture_size : 5
size_micropost_user : 50
microposts_number_page : 10
resize_to_limit: [400, 400]
